pacs:
  hostname: 172.20.112.1
  port: 4242
  aet: ORTHANC
local:
  port: 4000
  aet: SAMPLE_AE
request:
  type: c-move
  model: patient
  threads: 16
  throttle_time: 0.0
  elements_batch_file: /home/therlaup/DICOM-batch-export/config/sample-c-move-batch.csv
  elements:
    - StudyInstanceUID
    - SeriesInstanceUID
    - QueryRetrieveLevel=SERIES
anonymization:
  enabled: true
  script: /home/therlaup/DICOM-batch-export/config/sample-dicom-anonymizer.script
  lookup_table: /home/therlaup/DICOM-batch-export/config/sample-lookup-table.properties
output:
  directory: /home/therlaup/DICOM-batch-export/data
  database_file: /home/therlaup/DICOM-batch-export/data/database-c-move.csv
  directory_structure: PatientID/StudyInstanceUID
  filename: InstanceNumber
  decompress: True

  