pacs:
  hostname: 10.128.228.146
  port: 5000
  aet: ALI_QUERY_SCP
local:
  port: 4000
  aet: MHI_RTX_01
request:
  type: c-move
  model: patient
  threads: 8
  throttle_time: 0
  elements_batch_file: /volume/C-find/c-find_XA_2023.csv
  elements:
    - PatientID=*
    - StudyInstanceUID=*
    - QueryRetrieveLevel=STUDY ##Series if you want individual dicoms
schedule:
  enabled: True
  start_time: '18:30'
  end_time: '6:45'
  timezone: America/New_York
anonymization:
  enabled: True
  script: /volume/pydicom-batch/config/sample-dicom-anonymizer.script
  lookup_table: /volume/pydicom-batch/config/sample-lookup-table.properties
output:
  directory: /media/data1/ravram/DeepCORO/2023/
  database_file: /volume/pydicom-batch/data/extract/database-c-find_ANGIOGRAM2022_20230101-20231231.XA.csv
  directory_structure: PatientID/StudyInstanceUID
  filename: SeriesInstanceUID
  decompress: False