pacs:
  hostname: 172.20.112.1
  port: 4242
  aet: ORTHANC
local:
  port: 4000
  aet: SAMPLE_AE
request:
  type: c-find
  model: patient
  threads: 8
  throttle_time: 1.0
  elements_batch_file: /home/therlaup/DICOM-batch-export/config/sample-c-find-batch.csv
  elements:
    - PatientID=02004950
    - PatientName
    - Date
    - StudyTime
    - StudyDate
    - AccessionNumber
    - StudyInstanceUID
    - SeriesInstanceUID
    - QueryRetrieveLevel=SERIES
    - Modality
    - (0020,1208)
    - (0020,1206)
    - (0008,1030)
    - (0008,103E)
output:
  anonymization_script: /home/therlaup/DICOM-batch-export/config/sample-dicom-anonymizer.script
  anonymization_lookup_table: /home/therlaup/DICOM-batch-export/config/sample-lookup-table.properties
  directory: /home/therlaup/DICOM-batch-export/data
  database_file: /home/therlaup/DICOM-batch-export/data/database-c-find.csv
  directory_structure: PatientID/StudyInstanceUID/

  