pacs:
  hostname: 172.20.112.1
  port: 4242
  aet: ORTHANC
local:
  port: 4000
  aet: SAMPLE_AE
request:
  type: c-move
  model: patient
  threads: 4
  throttle_time: 0.0
  elements_batch_file: /home/therlaup/DICOM-batch-export/config/sample-c-move-batch.csv
  elements:
    - StudyInstanceUID
    - SeriesInstanceUID
    - QueryRetrieveLevel=SERIES
output:
  anonymization_script: /home/therlaup/DICOM-batch-export/config/sample-dicom-anonymizer.script
  anonymization_lookup_table: /home/therlaup/DICOM-batch-export/config/sample-lookup-table.properties
  directory: /home/therlaup/DICOM-batch-export/data
  database_file: /home/therlaup/DICOM-batch-export/data/library.csv
  directory_structure: PatientID/StudyInstanceUID/

  